blank_issues_enabled: false
contact_links:
- name: ğŸ“ï¸â€‚ Learn More
  about: Not sure where to start? Read our contributing guide to learn more.
  url: https://github.com/QuanTizEd8/testrepo002/blob/main/CONTRIBUTING.md
- name: ğŸ’¬â€‚ Contact Us
  about: Have another inquiry or need help? Contact us directly!
  url: https://quantized8.github.io/testrepo002/help/contact
